# Generated by Django 2.2.6 on 2020-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('width', models.IntegerField(default=60)),
                ('height', models.IntegerField(default=60)),
            ],
        ),
    ]
